name: Renovate

on:
  push:
    branches: [main, dev, test]
  schedule:
    # 每天凌晨 1 點執行
    - cron: '0 1 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: 'debug'
